//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Converter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atmp ; çˆ±ä»–ç¾Ž ;0-6 m  ;æ–°PREæ®µ;800 g;156;16;4;0.85;20.85;0;900
        ///atm1 ; çˆ±ä»–ç¾Ž ;0-6 m ;æ–°1æ®µ;800 g;153;15.5;4;0.85;20.35;0;900
        ///atm2 ; çˆ±ä»–ç¾Ž ;6-10 m;æ–°2æ®µ;800 g;153;15.5;4;0.85;20.35;0;900
        ///atm3 ; çˆ±ä»–ç¾Ž ;10-12 m;æ–°3æ®µ;800 g;153;15.5;4;0.85;20.35;0;900
        ///atm1+ ; çˆ±ä»–ç¾Ž ;&gt;12 m;æ–°1+æ®µ;600 g;102;9.49;3.5;0.6;13.59;0;700
        ///atm2+ ; çˆ±ä»–ç¾Ž ;&gt;24 m;æ–°2+æ®µ;600 g;102;9.49;3.5;0.6;13.59;0;700
        ///atmas ; çˆ±ä»–ç¾Ž ;0-24 m;æ·±åº¦æ°´è§£æ°¨åŸºé…¸å¥¶ç²‰ AS;400 g;348;41.39;1.1;0.85;46.379;0;500
        ///am [rest of string was truncated]&quot;;.
        /// </summary>
        public static string csvProduct {
            get {
                return ResourceManager.GetString("csvProduct", resourceCulture);
            }
        }
    }
}
